services:
  blog_chirpy:
    image: blog-chirpy-env
    container_name: blog_chirpy_env
    restart: always
    volumes:
      - .:/srv/jekyll # 当前目录挂载到容器
    ports:
      - "8080:4000" # 映射 Jekyll 默认端口
      - "35730:35729" # 映射 Jekyll 默认端口
    command: >
      sh -c "rm -rf _site && bundle install && bundle exec jekyll serve --host 0.0.0.0 -P 4000 -I -w -l"
